### ISSUE TITLE
0.11.0: `Parser` iterator item no longer implements `Borrow`?

### ISSUE THREAD

**Issue by chriskrycho** [pulldown-cmark/pulldown-cmark#891]
I use `pulldown-cmark-to-cmark` in a couple places, and it has a signature like so:

```rust
pub fn cmark<'a, I, E, F>(events: I, mut formatter: F) -> Result<State<'a>, fmt::Error>
where
    I: Iterator<Item = E>,
    E: Borrow<Event<'a>>,
    F: fmt::Write,
{
    ///
}
```

This was fine in 0.10.3, but no longer works with 0.11.0, because the item yielded by the iterator apparently no longer implements `Borrow<Event<'a>>`.

If this was intentional, that seems fine—the library will just need to update to account for the change! If so, would you be so kind as to document it as a breaking change in the release notes? 🙏🏼 (I poked around through the history a little but haven’t yet isolated where the change happened—only spent about five minutes doing that though.)

If it was unintentional, I am happy to help get a commit in so the items implement `Borrow` once again. (I am not blocked on this—I am just using 0.10.3 for the moment—but I do also have the time to contribute, so let me know!)

**Comment by ollpu** [comment]
As far as I can see, `Borrow<Event>` is still implemented for `Event`.

Is this because `pulldown-cmark-to-cmark` depends on v0.10.3, but you're trying to provide Events from the new version? If so, the library just needs an update.

I.e. the bound is really `E: Borrow<pulldown_cmark{0.10}::Event>` and you get a misleading error.

**Comment by chriskrycho** [comment]
Ah, interesting. That may well be, in which case the compiler error was (understandably!) misleading. I will patch the library on Monday and see if that is all it is! Thanks!

**Comment by Martin1887** [comment]
Sorry for the delay. Was this fixed? Thanks!

**Comment by chriskrycho** [comment]
@Martin1887 sorry in turn for my own delayed response here – I can confirm that the issue is as @ollpu suggested:

```
error[E0271]: expected `Parser<'_>` to be an iterator that yields `Event<'_>`, but it yields `Event<'_>`
   --> src/lib.rs:372:39
    |
372 |             html::push_html(&mut buf, events);
    |             ---------------           ^^^^^^ expected `Event<'_>`, found `pulldown_cmark::Event<'_>`
    |             |
    |             required by a bound introduced by this call
    |
    = note: `pulldown_cmark::Event<'_>` and `Event<'_>` have similar names, but are actually distinct types
note: `pulldown_cmark::Event<'_>` is defined in crate `pulldown_cmark`
   --> /Users/chris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pulldown-cmark-0.10.3/src/lib.rs:354:1
    |
354 | pub enum Event<'a> {
    | ^^^^^^^^^^^^^^^^^^
note: `Event<'_>` is defined in crate `pulldown_cmark`
   --> /Users/chris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pulldown-cmark-0.11.0/src/lib.rs:366:1
    |
366 | pub enum Event<'a> {
    | ^^^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `pulldown_cmark` are being used?
```

The issue is mdbook itself, so I’ll see about fixing that! Thanks.
